/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin Google OAuth */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google's consent screen. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback
         * @description Verifies the id_token, upserts the user by google_sub, encrypts and stores the refresh token, sets the session cookie, then redirects new users to /onboarding and returning users to /map.
         */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect into the web app with the session cookie set. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Development-only login
         * @description Returns 404 in production.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        display_name: string;
                    };
                };
            };
            responses: {
                /** @description Session cookie set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in user with group and active week context. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                            group?: components["schemas"]["Group"] | null;
                            activeWeek?: components["schemas"]["Week"] | null;
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/fitbit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect the Health API
         * @description Revokes and clears the stored (encrypted) refresh token.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["Unauthenticated"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile fields. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update my profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        display_name?: string;
                        weekly_step_target?: number;
                        avatar_skin?: number;
                        avatar_hair?: number;
                        avatar_colorway?: number;
                    };
                };
            };
            responses: {
                /** @description Updated profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        trace?: never;
    };
    "/api/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifetime stats for the profile screen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregate stats. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_steps_alltime?: number;
                            total_steps_this_week?: number;
                            city_wins?: number;
                            bingo_lines_alltime?: number;
                            /** @description Consecutive most-recent closed weeks with a city badge. */
                            current_streak?: number;
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a group
         * @description Creator becomes admin and member; the first week is created immediately.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description The new group (includes the invite code). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            group?: components["schemas"]["Group"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a group by invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        invite_code: string;
                    };
                };
            };
            responses: {
                /** @description Joined. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            group?: components["schemas"]["Group"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description GROUP_FULL — the group already has 8 players. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My group and members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Group with member list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            group?: components["schemas"]["Group"];
                            members?: components["schemas"]["Member"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/me/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave my group
         * @description Dissolves the leaver's nemesis matchup (opponent re-pairs with the bye or becomes the bye). If the admin leaves, the oldest remaining member is promoted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/me/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member (admin only)
         * @description Same nemesis re-pair semantics as leaving.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Admin cannot remove themselves — use leave. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weeks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composed Map screen payload */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Week, current/next city, route, progress strip, leaderboard with delta vs last week, countdown, lastSyncedAt, and screen state. All fields are null/empty with state "no_group" when the user has no group. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            week?: components["schemas"]["Week"] | null;
                            city?: components["schemas"]["City"] | null;
                            nextCity?: components["schemas"]["City"] | null;
                            selenaLeadSteps?: number;
                            route?: {
                                city_id?: number;
                                name?: string;
                                visited?: boolean;
                            }[];
                            progressStrip?: (components["schemas"]["Member"] & {
                                steps?: number;
                                target?: number;
                                pct?: number;
                            })[];
                            leaderboard?: (components["schemas"]["Member"] & {
                                rank?: number;
                                steps?: number;
                                deltaVsLastWeek?: number;
                            })[];
                            /** Format: date-time */
                            countdown?: string | null;
                            /** Format: date-time */
                            lastSyncedAt?: string | null;
                            /** @enum {string} */
                            state?: "in_progress" | "closing_soon" | "arrival" | "no_group";
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current city with landmark states and group workout status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description City dossier for the active week. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            city?: components["schemas"]["City"];
                            landmarks?: (components["schemas"]["Landmark"] & {
                                /** @enum {string} */
                                state?: "locked" | "unlocked" | "today";
                            })[];
                            groupWorkout?: {
                                total_members?: number;
                                worked_out_today?: number;
                                members?: (components["schemas"]["Member"] & {
                                    worked_out?: boolean;
                                })[];
                            };
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Past-city trophy view
         * @description Fully revealed, read-only view of the most recent closed week the group spent in this city. FORBIDDEN until such a week exists (future cities, and the current city until rollover closes it).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trophy view. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            city?: components["schemas"]["City"];
                            week?: {
                                /** Format: date */
                                starts_on?: string;
                                /** Format: date */
                                ends_on?: string;
                                group_target_steps?: number;
                                group_total_steps?: number | null;
                                target_hit?: boolean | null;
                            };
                            landmarks?: (components["schemas"]["Landmark"] & {
                                earned?: boolean;
                            })[];
                            unlocked_count?: number;
                            champion?: (components["schemas"]["Member"] & {
                                /** @enum {string|null} */
                                quality?: "bronze" | "silver" | "gold" | null;
                            }) | null;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This week's prediction state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Others' predictions are the string "hidden" until everyone has submitted or Monday noon (group tz), whichever comes first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            week?: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: date */
                                starts_on?: string;
                                /** Format: date */
                                ends_on?: string;
                                /** @enum {string} */
                                status?: "active" | "closed";
                            };
                            city?: {
                                name?: string;
                            };
                            myPrediction?: components["schemas"]["Prediction"] | null;
                            others?: "hidden" | components["schemas"]["Prediction"][];
                            allSubmitted?: boolean;
                            liveGroupTotal?: number;
                            /** Format: date-time */
                            revealAt?: string;
                            /** @enum {string} */
                            state?: "pending" | "partial" | "revealed" | "final";
                            submissionOpen?: boolean;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My results for closed weeks + lifetime wins */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            history?: {
                                /** Format: uuid */
                                week_id?: string;
                                /** Format: date */
                                starts_on?: string;
                                city_name?: string;
                                predicted_steps?: number;
                                actual_steps?: number | null;
                                actual_delta?: number | null;
                                is_winner?: boolean | null;
                            }[];
                            wins?: number;
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit my prediction
         * @description Window is the week's first day only (group tz).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        predicted_steps: number;
                    };
                };
            };
            responses: {
                /** @description Submitted. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            prediction?: components["schemas"]["Prediction"];
                        };
                    };
                };
                /** @description PREDICTION_CLOSED or PREDICTION_EXISTS. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bingo/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My bingo card for the active week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Card plus friends' progress. Tiles are server-detected only. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            card?: {
                                /** Format: uuid */
                                id?: string;
                                tiles?: components["schemas"]["BingoTile"][];
                                bingo_lines?: number;
                                blackout?: boolean;
                                frozen?: boolean;
                            };
                            friends?: components["schemas"]["BingoFriend"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bingo/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Group members' bingo progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progress list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friends?: components["schemas"]["BingoFriend"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nemesis/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My nemesis duel this week
         * @description Lazily creates the week's pairings on first request.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description matchup/you/nemesis/outcome are null for bye and no_matchup states. weekMax is the largest single-day step count in the group this week (used to normalize the skyline). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            matchup?: components["schemas"]["NemesisMatchup"] | null;
                            you?: components["schemas"]["Member"] | null;
                            nemesis?: components["schemas"]["Member"] | null;
                            week?: {
                                /** Format: date */
                                starts_on?: string;
                                /** Format: date */
                                ends_on?: string;
                            };
                            /** Format: date */
                            today?: string;
                            weekMax?: number;
                            outcome?: string | null;
                            /** @enum {string} */
                            state?: "active" | "tiebreak" | "complete" | "bye" | "no_matchup";
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nemesis/reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Swap opponents with the bye player
         * @description One reroll per matchup; your old opponent becomes the bye.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The fresh matchup. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            matchup?: components["schemas"]["NemesisMatchup"];
                        };
                    };
                };
                /** @description REROLL_USED or REROLL_UNAVAILABLE (nobody unpaired). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My earned badges */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Newest first, joined with definitions and city names. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            badges?: components["schemas"]["Badge"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest 20 notifications, unread first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notifications?: components["schemas"]["Notification"][];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        ids?: number[];
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync my steps now
         * @description Pulls today from the Health API client, then runs landmark unlock, bingo, and nemesis day-close detection. Rate-limited to one run per 10 minutes per user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Synced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            /** Format: date-time */
                            syncedAt?: string;
                        };
                    };
                };
                /** @description RATE_LIMITED — wait before syncing again. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            display_name?: string;
            /** Format: uuid */
            group_id?: string | null;
            weekly_step_target?: number;
            avatar_skin?: number;
            avatar_hair?: number;
            avatar_colorway?: number;
            fitbit_connected?: boolean;
            /** Format: date-time */
            last_synced_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Public member projection embedded in many payloads. */
        Member: {
            /** Format: uuid */
            user_id?: string;
            display_name?: string;
            avatar_skin?: number;
            avatar_hair?: number;
            avatar_colorway?: number;
        };
        Group: {
            /** Format: uuid */
            id?: string;
            name?: string;
            invite_code?: string;
            /** Format: uuid */
            admin_id?: string;
            timezone?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Week: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            group_id?: string;
            city_id?: number;
            /** Format: date */
            starts_on?: string;
            /** Format: date */
            ends_on?: string;
            group_target_steps?: number;
            /** @enum {string} */
            status?: "active" | "closed";
            group_total_steps?: number | null;
            target_hit?: boolean | null;
        };
        City: {
            id?: number;
            name?: string;
            country?: string;
            route_order?: number;
            background_image?: string | null;
            lat?: number;
            lng?: number;
        };
        Landmark: {
            id?: number;
            day?: number;
            name?: string;
            fun_fact?: string;
            image?: string | null;
        };
        Prediction: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            week_id?: string;
            /** Format: uuid */
            user_id?: string;
            predicted_steps?: number;
            /** Format: date-time */
            submitted_at?: string;
            actual_delta?: number | null;
            is_winner?: boolean | null;
            display_name?: string;
            avatar_skin?: number;
            avatar_hair?: number;
            avatar_colorway?: number;
        };
        /** @description Denormalized JSONB tile (zod bingoTileSchema). Index 12 is the free space. */
        BingoTile: {
            challenge_id: number;
            /** @enum {string} */
            state: "incomplete" | "in_progress" | "complete";
            /** Format: date-time */
            completed_at?: string | null;
            /** @description Joined from challenge definitions. */
            label?: string;
            icon?: string;
        } | {
            /** @enum {boolean} */
            free: true;
            /** @enum {string} */
            state: "complete";
        };
        BingoFriend: components["schemas"]["Member"] & {
            bingo_lines?: number;
            blackout?: boolean;
        };
        NemesisMatchup: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            week_id?: string;
            /** Format: uuid */
            player_a?: string;
            /** Format: uuid */
            player_b?: string;
            /** @enum {string} */
            status?: "active" | "tiebreak" | "complete";
            score_a?: number;
            score_b?: number;
            /** Format: date */
            tiebreaker_date?: string | null;
            reroll_used?: boolean;
            /** @description Denormalized JSONB (zod nemesisDayResultSchema). */
            daily_results?: {
                /** Format: date */
                date?: string;
                a_steps?: number;
                b_steps?: number;
                /** @enum {string} */
                winner?: "a" | "b" | "tie";
            }[];
        };
        Badge: {
            /** Format: uuid */
            id?: string;
            code?: string;
            label?: string;
            description?: string;
            /** @enum {string|null} */
            quality?: "bronze" | "silver" | "gold" | null;
            city_id?: number | null;
            city_name?: string | null;
            /** Format: date-time */
            earned_at?: string;
        };
        Notification: {
            id?: number;
            /** @description achievement / social / alert variants. */
            kind?: string;
            message?: string;
            read?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description Success. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok?: boolean;
                };
            };
        };
        /** @description Missing or invalid session. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description FORBIDDEN. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description NOT_FOUND. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
